apiVersion: v1
kind: Service
metadata:
  name: haproxy
spec:
  type: NodePort          # Service über Node-IP erreichbar
  selector:
    app: haproxy          # Wählt HAProxy-Pods aus
  ports:
    - name: https
      port: 443           # Service-Port (Cluster-intern)
      targetPort: 8443     # Port im Container
      nodePort: 30443     # Externer NodePort

