apiVersion: v1
kind: Service
metadata:
  name: webserver-headless
spec:
  clusterIP: None          # Headless Service (kein Cluster-IP)
  selector:
    app: web               # WÃ¤hlt Webserver-Pods aus
  ports:
    - port: 80             # Service-Port
      targetPort: 80       # Container-Port
